[build]
  functions = "functions"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://66aab92b521aed23d39ece23--chimerical-horse-59e7c6.netlify.app" # Changez cette URL pour celle de votre frontend
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/send-email"
  to = "/.netlify/functions/send-email"
  status = 200

[[redirects]]
  from = "/sendmail"
  to = "/.netlify/functions/sendmail"
  status = 200
